version: 2
updates:
- package-ecosystem: maven
  directory: "/app/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/client/"
  schedule:
    interval: daily
    time: "19:10"
  open-pull-requests-limit: 10
