name: VueJs CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
#        node-version: [ 12.x, 14.x, 16.x ] # can't do 16.x due to no tests existing for this project yet
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: client/demo/package-lock.json

      - name: npm install
        run: npm install
        working-directory: ./client/demo

      - name: npm lint
        run: npm run lint
        working-directory: ./client/demo

      - name: npm build
        run: npm run build --if-present
        working-directory: ./client/demo

      - name: npm test
        run: npm test
        working-directory: ./client/demo
#
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
#      - name: Build with Maven
#        run: mvn --batch-mode --update-snapshots verify
#        working-directory: ./app
      - run: mkdir staging
      - run: zip -r ../../../staging/dist.zip *
        working-directory: ./client/demo/dist
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
